### ISSUE TITLE
Custom DataSet issues? RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by crypticsymmetry** [yl4579/StyleTTS-VC#2]
DataSet examples:

- libritts-460/train-clean-460/188/135249/188_135249_000013_000004.wav|jˈɛt ðiːz tˈuː wˈɜːði lˈeɪdiz wɜː nˌɑːt ˈɛnəmiz ʌv ˈæn; ɔnðə kˈɑːntɹɛɹi, ðeɪ wɜː ɹˈiəli kwˈaɪt fˈɑːnd ʌv hɜː, ænd wʊdhɐv dᵻfˈɛndᵻd hɜːɹ æz ðɛɹ ˈoʊn jˈʌŋ hæd ˈɛnɪwˌʌn ˈɛls ɐtˈækt hɜː.|205
- libritts-460/train-clean-460/2436/2481/2436_2481_000046_000002.wav|aɪ sˈɜːtʃt fɔːɹ ɪt, pɹˈaɪd ɪt lˈuːs sˈɔftli.|921
- libritts-460/train-clean-460/7720/105168/7720_105168_000004_000003.wav|hɪz nˈɑːlɪdʒ ʌvðə wˈeɪz ʌvðə dˈɛnɪzənz ʌvðə wˈɔːɾɚ tˈoʊld hˌɪm wˌɛɹ tə wˈeɪt fɔːɹ pˈɪsə.|33
- libritts-460/train-clean-460/3905/149791/3905_149791_000007_000001.wav|"ɪf kwˈiːn kˈuː ˈiː ˈoʊ kˈɑːŋkɚz tə mˈɑːɹoʊ, ʃiː woʊnt biː nˈaɪs tʊ ˌʌs, ænd ɪf ðə sˈuː dˈɪk kˈɑːŋkɚz, hiːl biː wˈɜːs."|897
- VCTK-Corpus/wav48/p298/p298_246.wav|ðɛɹˌɑːɹ dʒˈʌst tˈuː tˈʊɹnəmənts ɹɪmˈeɪnɪŋ.|1147
- VCTK-Corpus/wav48/p265/p265_005.wav|ʃiː kæn skˈuːp ðiːz θˈɪŋz ˌɪntʊ θɹˈiː ɹˈɛd bˈæɡz, ænd wiː wɪl ɡˌoʊ mˈiːt hɜː wˈɛnzdeɪ æt ðə tɹˈeɪn stˈeɪʃən.|1148
- VCTK-Corpus/wav48/p229/p229_232.wav|sˈæɾɚdˌeɪ ɪz ɡˈɔn.|1149
- VCTK-Corpus/wav48/p281/p281_041.wav|ɐ wˈiːk ɪz ɐ lˈɑːŋ tˈaɪm ɪn pˈɑːlətˌɪks.|1150
- VCTK-Corpus/wav48/p263/p263_473.wav|maɪ plˈeɪs ɪz ɪnðə kˈɪtʃən.|1151
- VCTK-Corpus/wav48/p312/p312_089.wav|hˈɪɹ, ðə fˈænz hɐvbɪn fæntˈæstɪk.|1152
- VCTK-Corpus/wav48/p306/p306_024.wav|ðɪs ɪz ɐ vˈɛɹi kˈɑːmən tˈaɪp ʌv bˈoʊ, wˈʌn ʃˈoʊɪŋ mˈeɪnli ɹˈɛd ænd jˈɛloʊ, wɪð lˈɪɾəl ɔːɹ nˈoʊ ɡɹˈiːn ɔːɹ blˈuː.|1153
- VCTK-Corpus/wav48/p243/p243_254.wav|aɪd ɹˈæðɚ plˈeɪ wˈɛl nˈɛkst wˈiːk ðɐn hˈɪɹ.|1154
- VCTK-Corpus/wav48/p376/p376_064.wav|"dʒˈɔːɹdʒ ɹˈɑːbɚtsən dɪskɹˈaɪbd ðə plˈæn æz ɐn aʊtɹˈeɪdʒəs ænd dɪsɡɹˈeɪsfəl dᵻsˈɪʒən."|1155
- VCTK-Corpus/wav48/p279/p279_234.wav|pəlˈiːs lˈeɪɾɚ sˈɛd ðə skˈiːm wʊd ˈɛnd ɪn noʊvˈɛmbɚ.|1156

```

{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 14, 'steps_per_epoch': 5788}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 14, 'steps_per_epoch': 5788}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 14, 'steps_per_epoch': 5788}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 14, 'steps_per_epoch': 5788}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 14, 'steps_per_epoch': 5788}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 14, 'steps_per_epoch': 5788}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 14, 'steps_per_epoch': 5788}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 14, 'steps_per_epoch': 5788}
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [4,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [5,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [6,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [8,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [9,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [11,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [12,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [13,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [14,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [15,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [16,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [17,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [18,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [19,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [20,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [21,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [22,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [24,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [25,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [26,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [28,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [29,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"
Traceback (most recent call last):
  File "/workspace/StyleTTS-VC/train_first.py", line 448, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/workspace/StyleTTS-VC/train_first.py", line 226, in main
    loss_reg = r1_reg(out, gt)
  File "/workspace/StyleTTS-VC/utils.py", line 60, in r1_reg
    grad_dout = torch.autograd.grad(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

```

With Multi-Gpu enabled:

```

../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [4,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [5,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [6,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [8,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [9,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [10,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/workspace/StyleTTS-VC/train_first.py", line 448, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/workspace/StyleTTS-VC/train_first.py", line 224, in main
    out, _ = model.discriminator(gt.unsqueeze(1), labels)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/StyleTTS-VC/models.py", line 200, in forward
    out, features = self.get_feature(x)
  File "/workspace/StyleTTS-VC/models.py", line 193, in get_feature
    x = l(x)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/StyleTTS-VC/models.py", line 130, in forward
    x = self._shortcut(x) + self._residual(x)
  File "/workspace/StyleTTS-VC/models.py", line 126, in _residual
    x = self.conv2(x)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1201, in _call_impl
    result = hook(self, input)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/utils/spectral_norm.py", line 107, in __call__
    setattr(module, self.name, self.compute_weight(module, do_power_iteration=module.training))
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/utils/spectral_norm.py", line 86, in compute_weight
    v = normalize(torch.mv(weight_mat.t(), u), dim=0, eps=self.eps, out=v)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)`
```

**Comment by crypticsymmetry** [comment]
Changed the config to reflect the amount of speakers, "n_domain: 1255"

**Comment by crypticsymmetry** [comment]
Should this work to load the pretrained model and update the dimensions to the correct shapes for the new amount of speakers? I'm unsure if it will break the model, but seems to be running at the moment.

`def load_checkpoint(model, optimizer, path, load_only_params=True, multigpu=True):
    state = torch.load(path, map_location='cpu')
    params = state['net']
    for key in model:
        print('%s loaded' % key)
        if key == 'discriminator' and key in params:
            print('%s loaded' % key)
            state_dict = params[key]
            old_size = state_dict['main.9.bias'].shape[0]
            new_size = 1255
            if new_size > old_size:
                # Add rows to the original tensors
                state_dict['main.9.bias'] = torch.cat([state_dict['main.9.bias'], torch.randn(new_size - old_size)])
                state_dict['main.9.weight_orig'] = torch.cat([state_dict['main.9.weight_orig'], torch.randn(new_size - old_size, 512, 1, 1)], dim=0)
                state_dict['main.9.weight_u'] = torch.cat([state_dict['main.9.weight_u'], torch.randn(new_size - old_size)])
            elif new_size < old_size:
                # Remove rows from the original tensors
                state_dict['main.9.bias'] = state_dict['main.9.bias'][:new_size]
                state_dict['main.9.weight_orig'] = state_dict['main.9.weight_orig'][:new_size]
                state_dict['main.9.weight_u'] = state_dict['main.9.weight_u'][:new_size]
            if multigpu:
                model[key].module.load_state_dict(state_dict)
   
            else:
                model[key].load_state_dict(state_dict)
         elif key in params:
            if multigpu:
                model[key].module.load_state_dict(params[key])
            else:
                model[key].load_state_dict(params[key])
    _ = [model[key].eval() for key in model]
    
    if not load_only_params:
        epoch = state["epoch"]
        iters = state["iters"]
        optimizer.load_state_dict(state["optimizer"])
    else:
        epoch = 0
        iters = 0
        
    return model, optimizer, epoch, iters`

**Comment by crypticsymmetry** [comment]
Will this work to reshape the pretrained model to the new data shape without breaking the model? **Edit**: Seems like its training fine!
```
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 20, 'steps_per_epoch': 2894}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 20, 'steps_per_epoch': 2894}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 20, 'steps_per_epoch': 2894}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 20, 'steps_per_epoch': 2894}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 20, 'steps_per_epoch': 2894}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 20, 'steps_per_epoch': 2894}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 20, 'steps_per_epoch': 2894}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 20, 'steps_per_epoch': 2894}
discriminator loaded
Epoch [1/20], Step [10/2894], Mel Loss: 0.26010, Adv Loss: 0.84298, Disc Loss: 1.54393, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.03459, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 33.32503700256348
Epoch [1/20], Step [20/2894], Mel Loss: 0.23848, Adv Loss: 0.77434, Disc Loss: 1.52789, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.03315, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 56.26371741294861
Epoch [1/20], Step [30/2894], Mel Loss: 0.22786, Adv Loss: 0.75827, Disc Loss: 1.57081, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.03072, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 81.08041477203369
Epoch [1/20], Step [40/2894], Mel Loss: 0.23075, Adv Loss: 0.77105, Disc Loss: 1.62789, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.02603, Feat Loss: 0.00000, Cycle Loss: 0.00000
```

```
def load_checkpoint(model, optimizer, path, load_only_params=True, multigpu=True):
    state = torch.load(path, map_location='cpu')
    params = state['net']
    for key in model:
        if key == 'discriminator' and key in params:
            print('%s loaded' % key)
            state_dict = params[key]
            old_size = state_dict['main.9.bias'].shape[0]
            new_size = 1255
            if new_size > old_size:
                # Add rows to the original tensors
                state_dict['main.9.bias'] = torch.cat([state_dict['main.9.bias'], torch.randn(new_size - old_size)])
                state_dict['main.9.weight_orig'] = torch.cat([state_dict['main.9.weight_orig'], torch.randn(new_size - old_size, 512, 1, 1)], dim=0)
                state_dict['main.9.weight_u'] = torch.cat([state_dict['main.9.weight_u'], torch.randn(new_size - old_size)])
            elif new_size < old_size:
                # Remove rows from the original tensors
                state_dict['main.9.bias'] = state_dict['main.9.bias'][:new_size]
                state_dict['main.9.weight_orig'] = state_dict['main.9.weight_orig'][:new_size]
                state_dict['main.9.weight_u'] = state_dict['main.9.weight_u'][:new_size]
            if multigpu:
                model[key].module.load_state_dict(state_dict)
            else:
                model[key].load_state_dict(state_dict)
        elif key in params:
            if multigpu:
                model[key].module.load_state_dict(params[key])
            else:
                model[key].load_state_dict(params[key])
    _ = [model[key].eval() for key in model]
    
    if not load_only_params:
        epoch = state["epoch"]
        iters = state["iters"]
        optimizer.load_state_dict(state["optimizer"])
    else:
        epoch = 0
        iters = 0
        
    return model, optimizer, epoch, iters
```

**Comment by yl4579** [comment]
Yes, but you don't need to manually load the weights this way. I have a function that automatically does this. Please check https://github.com/yl4579/StarGANv2-VC/blob/main/trainer.py#L101

**Comment by Superman-Valencia** [comment]
[train_list.txt](https://github.com/yl4579/StyleTTS-VC/files/10906932/train_list.txt)
[val_list.txt](https://github.com/yl4579/StyleTTS-VC/files/10906933/val_list.txt)
I tried my own datasets, and changed the n_domain to 4, but an error occurred:

2023-03-07 16:04:16.826425: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1016}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1016}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1016}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1016}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1016}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1016}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1016}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1016}
Epoch [1/150], Step [10/1016], Mel Loss: 0.70452, Adv Loss: 0.68080, Disc Loss: 1.38663, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00249, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 16.253488779067993
Epoch [1/150], Step [20/1016], Mel Loss: 0.61824, Adv Loss: 0.69503, Disc Loss: 1.38415, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00030, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 27.55336308479309
Epoch [1/150], Step [30/1016], Mel Loss: 0.59486, Adv Loss: 0.69701, Disc Loss: 1.38375, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00008, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 39.67645025253296
Epoch [1/150], Step [40/1016], Mel Loss: 0.58141, Adv Loss: 0.71333, Disc Loss: 1.36781, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00021, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 51.58302068710327
Epoch [1/150], Step [50/1016], Mel Loss: 0.57084, Adv Loss: 0.66128, Disc Loss: 1.33899, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00016, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 63.373833894729614
Epoch [1/150], Step [60/1016], Mel Loss: 0.55968, Adv Loss: 0.71430, Disc Loss: 1.33997, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00093, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 74.5131196975708
Epoch [1/150], Step [70/1016], Mel Loss: 0.57422, Adv Loss: 0.80370, Disc Loss: 1.24898, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00034, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 86.42226362228394
Epoch [1/150], Step [80/1016], Mel Loss: 0.54205, Adv Loss: 0.78441, Disc Loss: 1.25569, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00031, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 97.52225136756897
Epoch [1/150], Step [90/1016], Mel Loss: 0.54150, Adv Loss: 0.75054, Disc Loss: 1.21147, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00042, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 109.00170564651489
Epoch [1/150], Step [100/1016], Mel Loss: 0.52815, Adv Loss: 0.95741, Disc Loss: 1.09224, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00036, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 120.83172011375427
Epoch [1/150], Step [110/1016], Mel Loss: 0.51254, Adv Loss: 0.71154, Disc Loss: 1.24625, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00024, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 133.21448493003845
Epoch [1/150], Step [120/1016], Mel Loss: 0.52700, Adv Loss: 0.72580, Disc Loss: 1.45188, Mono Loss: 0.00000, S2S Loss: 0.00000, Style Loss: 0.00018, Feat Loss: 0.00000, Cycle Loss: 0.00000
Time elasped: 144.92662048339844
Traceback (most recent call last):
  File "c:/Users/machenike/Desktop/read_paper/StyleTTS-AC/train_first.py", line 448, in <module>
    main()
  File "D:\python\envs\CVAE\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\python\envs\CVAE\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\python\envs\CVAE\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\python\envs\CVAE\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:/Users/machenike/Desktop/read_paper/StyleTTS-AC/train_first.py", line 145, in main
    for i, batch in enumerate(train_dataloader):
  File "D:\python\envs\CVAE\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "D:\python\envs\CVAE\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "D:\python\envs\CVAE\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "D:\python\envs\CVAE\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\python\envs\CVAE\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\python\envs\CVAE\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\python\envs\CVAE\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\Users\machenike\Desktop\read_paper\StyleTTS-AC\meldataset.py", line 109, in __getitem__
    ref_mel_tensor, ref_label = self._load_data(ref_data)
  File "c:\Users\machenike\Desktop\read_paper\StyleTTS-AC\meldataset.py", line 136, in _load_data
    wave, text_tensor, speaker_id = self._load_tensor(data)
  File "c:\Users\machenike\Desktop\read_paper\StyleTTS-AC\meldataset.py", line 115, in _load_tensor
    speaker_id = int(speaker_id)
ValueError: invalid literal for int() with base 10: ''


It seems that there is space in speaker_id but I print the type(speaker_id) and len(speaker_id), find nothing wrong. Could you help me? Thank you very much!

**Comment by yl4579** [comment]
@Superman-Valencia The error means your `speaker_id` here is not exactly integer. You can use regex to remove any non-integer characters using regex, for example:

```python
import re
speaker_id = re.findall(r'\d+', speaker_id)
speaker_id = int(''.join(speaker_id))
```

**Comment by Superman-Valencia** [comment]
Oh,thank you very much！ 
And I set the validation of build_dataloader to False may also resolve the problem, which means the drop_last is true. It seems that the length of training data need to be divided by batch_size if drop_last is false.
