### ISSUE TITLE
cycle loss curve

### ISSUE THREAD

**Issue by little-duan** [yl4579/StyleTTS-VC#5]
thank you for your great work. i trained the model on my own data, and the cycle loss curve is like this pic, is that normal? would you please share you loss curve.
![713514346](https://user-images.githubusercontent.com/61343750/236373418-60500e55-7ef0-4bd4-83fb-c7d498332514.jpg)

**Comment by yl4579** [comment]
Sorry for the late reply I'm busy with another project. Was this the first or second stage? It seems like it's the first stage, which means the acoustic model is diverging. Have you tried to train on the same dataset with StyleTTS of the first stage?

**Comment by little-duan** [comment]
i made a mistake on my acoustic model, thank you very much.

**Comment by chiaki-luo** [comment]
How can I konw that the first stage training is ok? Whether it is ok for the 0.2 mel loss?

**Comment by yl4579** [comment]
@chiaki-luo The best way is to write a test code snippet and listen to the reconstructed speech. Unfortunately I didn't include it in the Tensorboard log because you need a vocoder to convert the mel-spectrogram to waveforms, but you can easily write the testing code to check the quality.
