### ISSUE TITLE
Inference with text as input

### ISSUE THREAD

**Issue by vbrydik** [yl4579/StyleTTS-VC#8]
Hello! Great repository, I've tried voice cloning and it works reasonably well. I want to try to use text as input with the code in this repository, but didn't succeed yet.

Is there a way to do this, because in inference demo it's only audio as input? Thanks!

**Comment by huyhuynh2210** [comment]
> Hello! Great repository, I've tried voice cloning and it works reasonably well. I want to try to use text as input with the code in this repository, but didn't succeed yet.
> 
> Is there a way to do this, because in inference demo it's only audio as input? Thanks!

Hello! I had difficulty initializing the env and luckily you were able to run this repo, can you share the requirements.txt file? thanks!

**Comment by yl4579** [comment]
@vbrydik It is difficult for me to find the code to do text-guided voice conversion because this project has been two years old. Can you provide the code you have now and its output?

**Comment by vbrydik** [comment]
Hi, sorry for late response.

@huyhuynh2210 I'll try send the requirements.txt here tomorrow.

@yl4579 The code currently is in form of a notebook and is really messy, I'll clean this up a little bit and will send here. It's basically modified inference notebook. Also the output audio I got from it is unintelligible, so I might've done something completely wrong. Hoped you had a ready solution :)

**Comment by vbrydik** [comment]
I lost my access to cloud machine I've been using, so I can't extract the requirements.txt file and code for this issue, sorry for inconvenience. I've tried StyleTTS repo and it does what I need. Thanks everyone, I'm closing this issue
